name: Cypress Tests

on:
  push:
    branches:
      - EX04
  pull_request:
    branches:
      - EX04

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    container:
      image: cypress/browsers:node-22.11.0-chrome-130.0.6723.69-1-ff-132.0-edge-130.0.2849.56-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress (EX04-pom.cy.js only)
        run: npx cypress run --spec "cypress/e2e/assignment4/EX04-pom.cy.js" --record --key ${{ secrets.CYPRESS_KEY }}

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/**/*.mp4

      - name: Upload Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/**/*.png
